version: '2'
services:
  api:
    build: .
    ports:
     - "5000:5000"
    depends_on:
      - web
    links:
      - "web:api"
  web:
    image: odoo:10.0
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
